kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: coffee-shop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: coffee-shop
    spec:
      containers:
      - name: coffee-shop
        image: docker.sebastian-daschner.com/coffee-shop:1
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-c"
            - "curl -f localhost:8080/"
          initialDelaySeconds: 10
        readinessProbe:
          exec:
            command:
            - "/bin/bash"
            - "-c"
            - "curl -f localhost:8080/coffee-shop/resources/health"
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 2
        lifecycle:
          preStop:
            exec:
              command: ["/bin/bash", "-c", "/deactivate-health-check.sh && sleep 20"]
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
