apiVersion: v1
appVersion: 1.0.20
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/liberty.png
name: zero-downtime-kubernetes
version: 1.0.20
